query ListTeamMembers @auth(level: PUBLIC) {
  teamMembers {
    id
    name
    role
    photoUrl
  }
}

query GetAgencyInfo @auth(level: PUBLIC) {
  agencyInfos {
    name
    description
    tagline
    address
    contactEmail
    phoneNumber
    foundingYear
    missionStatement
  }
}

query ListServices @auth(level: PUBLIC) {
  services {
    id
    title
    description
    detailedDescription
    features
    iconUrl
  }
}

query ListTestimonials @auth(level: PUBLIC) {
  testimonials {
    id
    clientName
    clientTitle
    clientCompany
    clientLogoUrl
    quote
  }
}