extend type AgencyInfo {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "AgencyInfo", purpose: IMPLICIT_KEY_FIELD)
}
extend type PageSection {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PageSection", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PageSection`.`videoAsset`. It must match the value of `VideoAsset`.`id`. See `@ref` for how to customize it.
  """
  videoAssetId: UUID @fdc_generated(from: "PageSection.videoAsset", purpose: IMPLICIT_REF_FIELD)
}
extend type Service {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Service", purpose: IMPLICIT_KEY_FIELD)
}
extend type TeamMember {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "TeamMember", purpose: IMPLICIT_KEY_FIELD)
}
extend type Testimonial {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Testimonial", purpose: IMPLICIT_KEY_FIELD)
}
extend type VideoAsset {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "VideoAsset", purpose: IMPLICIT_KEY_FIELD)
}
