extend type Mutation {
  """
  ✨ Insert a single `AgencyInfo` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  agencyInfo_insert(
    """
    Data object to insert into the table.
    """
    data: AgencyInfo_Data!
  ): AgencyInfo_KeyOutput! @fdc_generated(from: "AgencyInfo", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PageSection` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  pageSection_insert(
    """
    Data object to insert into the table.
    """
    data: PageSection_Data!
  ): PageSection_KeyOutput! @fdc_generated(from: "PageSection", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Service` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  service_insert(
    """
    Data object to insert into the table.
    """
    data: Service_Data!
  ): Service_KeyOutput! @fdc_generated(from: "Service", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TeamMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teamMember_insert(
    """
    Data object to insert into the table.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput! @fdc_generated(from: "TeamMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Testimonial` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  testimonial_insert(
    """
    Data object to insert into the table.
    """
    data: Testimonial_Data!
  ): Testimonial_KeyOutput! @fdc_generated(from: "Testimonial", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `VideoAsset` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  videoAsset_insert(
    """
    Data object to insert into the table.
    """
    data: VideoAsset_Data!
  ): VideoAsset_KeyOutput! @fdc_generated(from: "VideoAsset", purpose: INSERT_SINGLE)
  """
  ✨ Insert `AgencyInfo` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  agencyInfo_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [AgencyInfo_Data!]!
  ): [AgencyInfo_KeyOutput!]! @fdc_generated(from: "AgencyInfo", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PageSection` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  pageSection_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PageSection_Data!]!
  ): [PageSection_KeyOutput!]! @fdc_generated(from: "PageSection", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Service` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  service_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Service_Data!]!
  ): [Service_KeyOutput!]! @fdc_generated(from: "Service", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TeamMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  teamMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TeamMember_Data!]!
  ): [TeamMember_KeyOutput!]! @fdc_generated(from: "TeamMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Testimonial` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  testimonial_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Testimonial_Data!]!
  ): [Testimonial_KeyOutput!]! @fdc_generated(from: "Testimonial", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `VideoAsset` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  videoAsset_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [VideoAsset_Data!]!
  ): [VideoAsset_KeyOutput!]! @fdc_generated(from: "VideoAsset", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `AgencyInfo` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AgencyInfo`.
  """
  agencyInfo_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: AgencyInfo_Data!
  ): AgencyInfo_KeyOutput! @fdc_generated(from: "AgencyInfo", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PageSection` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PageSection`.
  """
  pageSection_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PageSection_Data!
  ): PageSection_KeyOutput! @fdc_generated(from: "PageSection", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Service` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Service`.
  """
  service_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Service_Data!
  ): Service_KeyOutput! @fdc_generated(from: "Service", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TeamMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TeamMember`.
  """
  teamMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput! @fdc_generated(from: "TeamMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Testimonial` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Testimonial`.
  """
  testimonial_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Testimonial_Data!
  ): Testimonial_KeyOutput! @fdc_generated(from: "Testimonial", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `VideoAsset` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VideoAsset`.
  """
  videoAsset_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: VideoAsset_Data!
  ): VideoAsset_KeyOutput! @fdc_generated(from: "VideoAsset", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `AgencyInfo` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `AgencyInfo`.
  """
  agencyInfo_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [AgencyInfo_Data!]!
  ): [AgencyInfo_KeyOutput!]! @fdc_generated(from: "AgencyInfo", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PageSection` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PageSection`.
  """
  pageSection_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PageSection_Data!]!
  ): [PageSection_KeyOutput!]! @fdc_generated(from: "PageSection", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Service` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Service`.
  """
  service_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Service_Data!]!
  ): [Service_KeyOutput!]! @fdc_generated(from: "Service", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TeamMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TeamMember`.
  """
  teamMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TeamMember_Data!]!
  ): [TeamMember_KeyOutput!]! @fdc_generated(from: "TeamMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Testimonial` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Testimonial`.
  """
  testimonial_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Testimonial_Data!]!
  ): [Testimonial_KeyOutput!]! @fdc_generated(from: "Testimonial", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `VideoAsset` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `VideoAsset`.
  """
  videoAsset_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [VideoAsset_Data!]!
  ): [VideoAsset_KeyOutput!]! @fdc_generated(from: "VideoAsset", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `AgencyInfo` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `AgencyInfo` or `null` if not found.
  """
  agencyInfo_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AgencyInfo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AgencyInfo_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: AgencyInfo_Data!
  ): AgencyInfo_KeyOutput @fdc_generated(from: "AgencyInfo", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PageSection` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PageSection` or `null` if not found.
  """
  pageSection_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PageSection_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PageSection_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PageSection_Data!
  ): PageSection_KeyOutput @fdc_generated(from: "PageSection", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Service` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Service` or `null` if not found.
  """
  service_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Service_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Service_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Service_Data!
  ): Service_KeyOutput @fdc_generated(from: "Service", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TeamMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TeamMember` or `null` if not found.
  """
  teamMember_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TeamMember_Data!
  ): TeamMember_KeyOutput @fdc_generated(from: "TeamMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Testimonial` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Testimonial` or `null` if not found.
  """
  testimonial_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Testimonial_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Testimonial_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Testimonial_Data!
  ): Testimonial_KeyOutput @fdc_generated(from: "Testimonial", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `VideoAsset` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `VideoAsset` or `null` if not found.
  """
  videoAsset_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VideoAsset_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoAsset_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: VideoAsset_Data!
  ): VideoAsset_KeyOutput @fdc_generated(from: "VideoAsset", purpose: UPDATE_SINGLE)
  """
  ✨ Update `AgencyInfo` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  agencyInfo_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: AgencyInfo_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: AgencyInfo_Data!
  ): Int! @fdc_generated(from: "AgencyInfo", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PageSection` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  pageSection_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PageSection_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PageSection_Data!
  ): Int! @fdc_generated(from: "PageSection", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Service` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  service_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Service_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Service_Data!
  ): Int! @fdc_generated(from: "Service", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TeamMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  teamMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TeamMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TeamMember_Data!
  ): Int! @fdc_generated(from: "TeamMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Testimonial` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  testimonial_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Testimonial_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Testimonial_Data!
  ): Int! @fdc_generated(from: "Testimonial", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `VideoAsset` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  videoAsset_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: VideoAsset_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: VideoAsset_Data!
  ): Int! @fdc_generated(from: "VideoAsset", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `AgencyInfo` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  agencyInfo_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: AgencyInfo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: AgencyInfo_FirstRow
  ): AgencyInfo_KeyOutput @fdc_generated(from: "AgencyInfo", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PageSection` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  pageSection_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PageSection_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PageSection_FirstRow
  ): PageSection_KeyOutput @fdc_generated(from: "PageSection", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Service` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  service_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Service_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Service_FirstRow
  ): Service_KeyOutput @fdc_generated(from: "Service", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TeamMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  teamMember_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TeamMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TeamMember_FirstRow
  ): TeamMember_KeyOutput @fdc_generated(from: "TeamMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Testimonial` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  testimonial_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Testimonial_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Testimonial_FirstRow
  ): Testimonial_KeyOutput @fdc_generated(from: "Testimonial", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `VideoAsset` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  videoAsset_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: VideoAsset_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: VideoAsset_FirstRow
  ): VideoAsset_KeyOutput @fdc_generated(from: "VideoAsset", purpose: DELETE_SINGLE)
  """
  ✨ Delete `AgencyInfo` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  agencyInfo_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: AgencyInfo_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PageSection` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  pageSection_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PageSection_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PageSection", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Service` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  service_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Service_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Service", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TeamMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  teamMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TeamMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Testimonial` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  testimonial_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Testimonial_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `VideoAsset` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  videoAsset_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: VideoAsset_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset", purpose: DELETE_MULTIPLE)
}
