extend type AgencyInfo {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "AgencyInfo", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `AgencyInfo` table.
  """
  _count: Int! @fdc_generated(from: "AgencyInfo.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `address` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  address_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.address", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `contactEmail` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  contactEmail_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.contactEmail", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `foundingYear` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  foundingYear_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.foundingYear", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `missionStatement` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  missionStatement_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.missionStatement", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `phoneNumber` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  phoneNumber_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.phoneNumber", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `AgencyInfo` table where the `tagline` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  tagline_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "AgencyInfo.tagline", purpose: QUERY_COUNT)
  """
  ✨ Sum the `foundingYear` field in the `AgencyInfo` table.
  """
  foundingYear_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "AgencyInfo.foundingYear", purpose: QUERY_SUM)
  """
  ✨ Average the `foundingYear` field in the `AgencyInfo` table.
  """
  foundingYear_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "AgencyInfo.foundingYear", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `foundingYear` field in the `AgencyInfo` table.
  """
  foundingYear_min: Int @fdc_generated(from: "AgencyInfo.foundingYear", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `foundingYear` field in the `AgencyInfo` table.
  """
  foundingYear_max: Int @fdc_generated(from: "AgencyInfo.foundingYear", purpose: QUERY_MAX)
}
extend type PageSection {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "PageSection", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `PageSection` table.
  """
  _count: Int! @fdc_generated(from: "PageSection.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `bodyText` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bodyText_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.bodyText", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `heading` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  heading_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.heading", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `order` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  order_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.order", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PageSection` table where the `videoAssetId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  videoAssetId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PageSection.videoAssetId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `order` field in the `PageSection` table.
  """
  order_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "PageSection.order", purpose: QUERY_SUM)
  """
  ✨ Average the `order` field in the `PageSection` table.
  """
  order_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "PageSection.order", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `order` field in the `PageSection` table.
  """
  order_min: Int @fdc_generated(from: "PageSection.order", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `order` field in the `PageSection` table.
  """
  order_max: Int @fdc_generated(from: "PageSection.order", purpose: QUERY_MAX)
}
extend type Service {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Service", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Service` table.
  """
  _count: Int! @fdc_generated(from: "Service.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Service` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Service.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Service` table where the `detailedDescription` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  detailedDescription_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Service.detailedDescription", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Service` table where the `iconUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  iconUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Service.iconUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Service` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Service.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Service` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Service.title", purpose: QUERY_COUNT)
}
extend type TeamMember {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TeamMember", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TeamMember` table.
  """
  _count: Int! @fdc_generated(from: "TeamMember.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `bio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.bio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TeamMember` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TeamMember.role", purpose: QUERY_COUNT)
}
extend type Testimonial {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Testimonial", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Testimonial` table.
  """
  _count: Int! @fdc_generated(from: "Testimonial.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Testimonial` table where the `clientCompany` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientCompany_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial.clientCompany", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Testimonial` table where the `clientLogoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientLogoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial.clientLogoUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Testimonial` table where the `clientName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial.clientName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Testimonial` table where the `clientTitle` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  clientTitle_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial.clientTitle", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Testimonial` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Testimonial` table where the `quote` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  quote_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Testimonial.quote", purpose: QUERY_COUNT)
}
extend type VideoAsset {
  """
  ✨ List `PageSection` objects in a one-to-many relationship (where `PageSection`.`videoAsset` is this object).
  """
  pageSections_on_videoAsset(
    """
    Filter condition to narrow down the query results.
    """
    where: PageSection_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PageSection_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PageSection_Having
  ): [PageSection!]! @fdc_generated(from: "PageSection.videoAsset", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "VideoAsset", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `VideoAsset` table.
  """
  _count: Int! @fdc_generated(from: "VideoAsset.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoAsset` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoAsset` table where the `durationSeconds` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  durationSeconds_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset.durationSeconds", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoAsset` table where the `hlsManifestUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  hlsManifestUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset.hlsManifestUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoAsset` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoAsset` table where the `thumbnailUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  thumbnailUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset.thumbnailUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `VideoAsset` table where the `title` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  title_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "VideoAsset.title", purpose: QUERY_COUNT)
  """
  ✨ Sum the `durationSeconds` field in the `VideoAsset` table.
  """
  durationSeconds_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "VideoAsset.durationSeconds", purpose: QUERY_SUM)
  """
  ✨ Average the `durationSeconds` field in the `VideoAsset` table.
  """
  durationSeconds_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "VideoAsset.durationSeconds", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `durationSeconds` field in the `VideoAsset` table.
  """
  durationSeconds_min: Int @fdc_generated(from: "VideoAsset.durationSeconds", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `durationSeconds` field in the `VideoAsset` table.
  """
  durationSeconds_max: Int @fdc_generated(from: "VideoAsset.durationSeconds", purpose: QUERY_MAX)
}
