import { ChangeDetectionStrategy, Component } from '@angular/core';
import {FlauxSectionComponent} from '@app/shared/section/section.component';
import { FlauxBtnComponent } from "@app/shared/flaux-btn/flaux-btn.component";
import {LaserFlowComponent} from '@app/shared/laser-flow';
import { IconMarqueeComponent } from '@app/shared/icon-marquee';

@Component({
	selector: 'trunks-section',
	imports: [FlauxSectionComponent, FlauxBtnComponent, LaserFlowComponent, IconMarqueeComponent],
	templateUrl: './trunks-section.component.html',
	styleUrl: './trunks-section.component.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TrunksSectionComponent {
	aiMarqueeFiles: string[] = [
		'ActiveCampaign Trigger integration.svg',
		'Airtable integration.svg',
		'Anthropic Chat Model integration.svg',
		'APITemplate.io integration.svg',
		'Asana Trigger integration.svg',
		'Bitbucket Trigger integration.svg',
		'Brevo integration.svg',
		'Cal.com Trigger integration.svg',
		'Calendly Trigger integration.svg',
		'ClickUp Trigger integration.svg',
		'CoinGecko integration.svg',
		'Copper integration.svg',
		'DeepSeek Chat Model integration.svg',
		'Discord integration.svg',
		'Embeddings AWS Bedrock integration.svg',
		'Embeddings Azure OpenAI integration.svg',
		'Embeddings Hugging Face Inference integration.svg',
		'Embeddings Ollama integration.svg',
		'Facebook Trigger integration.svg',
		'Google Calendar Trigger integration.svg',
		'Google Drive integration.svg',
		'Google Gemini integration.svg',
		'Google PaLM Language Model integration.svg',
		'Google Sheets Trigger integration.svg',
		'Google Slides integration.svg',
		'HubSpot Trigger integration.svg',
		'Jira Trigger integration.svg',
		'Lemlist Trigger integration.svg',
		'LinkedIn integration.svg',
		'Magento 2 integration.svg',
		'Mailchimp integration.svg',
		'Mautic Trigger integration.svg',
		'Microsoft Excel 365 integration.svg',
		'Microsoft To Do integration.svg',
		'Monday.com integration.svg',
		'MongoDB integration.svg',
		'Notion Trigger integration.svg',
		'OpenAI integration.svg',
		'PayPal integration.svg',
		'Pipedrive Trigger integration.svg',
		'Raindrop integration.svg',
		'Salesforce integration.svg',
		'SendGrid integration.svg',
		'Shopify integration.svg',
		'Slack integration.svg',
		'Stripe integration.svg',
		'svgexport-1.svg',
		'Todoist integration.svg',
		'Trello Trigger integration.svg',
		'Webflow integration.svg',
		'WooCommerce integration.svg',
		'Wordpress integration.svg',
		'X (Formerly Twitter) integration.svg',
		'Zoho CRM integration.svg'
	];

	agencyMarqueeFiles: string[] = [
		'ad-placement-group.png',
		'Attract-convert-engage.png',
		'business-app-18299.png',
		'business-app-42842.png',
		'SM-AI-Knowledge_v1.png',
		'Capture-more-leads-with-converstations-ai-img.webp',
		'Conversations - custom1.png',
		'Copy of Reviews from top review sites.png',
		'Conversations AI - webchat.png',
		'Conversations SMS 3.png',
		'increase-productivity-2.png',
		'Local-SEO-group.png',
		'marketplace16779.png',
		'Multi-location Review Management2.png',
		'SM-AI-Knowledge_v2.png',
		'Reputation Management group.png',
		'Social Marketing post performance.png',
		'snapshot-18067.png',
		'sm3-2.png',
		'social-ads.png'
	]
}
